### ISSUE TITLE
strange error: Could not get cmap table size

### ISSUE THREAD

**Issue by jamesdixon** [peng8350/flutter_pulltorefresh#186] opened 2019-10-15 03:36 UTC
Hi, I get the following error when adding a SmartRefresher:

[VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:wingmom_app/enums.dart';
import 'package:wingmom_app/view_models/secure/services_view_model.dart';
import 'package:wingmom_app/views/base_view.dart';

class ServicesView extends StatefulWidget {
  @override
  _ServicesViewState createState() => _ServicesViewState();
}

class _ServicesViewState extends State<ServicesView> {
  final _refreshController = RefreshController();

  @override
  Widget build(BuildContext context) {
    return BaseView<ServicesViewModel>(
      onModelReady: (model) {
        model.getServices();
      },
      builder: (context, model, child) => CupertinoPageScaffold(
        child: model.state == ViewState.Busy
            ? Center(child: CupertinoActivityIndicator())
            : SmartRefresher(
                controller: _refreshController,
                enablePullDown: true,
                onRefresh: () async {
                  await model.getServices();
                  _refreshController.refreshCompleted();
                },
                child: Container()),
      ),
    );
  }

  void dipose() {
    _refreshController.dispose();
    super.dispose();
  }
}
```

Thank you in advance!

**Comment by peng8350** [comment] 2019-10-16 05:58
I think you should go to issue fluent. It's about font exceptions.

**Comment by jamesdixon** [comment] 2019-10-17 03:17
@peng8350 I found the issue.

I'm using CupertinoApp and with that, I disabled `uses-material-design` in my `pubspec.yaml` since I'm using `cupertino-icons`. That said, it looks like your package uses material icons and even though it's listed in `pubspec.yaml`, it's not being included which is what's causing the font exception to be thrown.

**Comment by peng8350** [comment] 2019-10-17 12:28
I copy your sample code and use CupertinoApp,but the problem cannot reproduce.

**Comment by peng8350** [comment] 2020-07-25 06:31
no one reply and got this issue ,so close it.

**Closed by peng8350** 2020-07-25 06:31 UTC
