### ISSUE TITLE
Add Null safe version

### ISSUE THREAD

**Issue by zhaopingfu** [peng8350/flutter_pulltorefresh#461] opened 2021-03-18 01:57 UTC
After Flutter is upgraded to `2.0.2`, it needs to support `null safety`. 

Currently version `1.6.4` does not support `null safety`. 

Please support `null safety`. 

Thank you.

**Comment by onlyYU** [comment] 2021-03-18 08:07
+1

**Comment by DasTobbel** [comment] 2021-03-18 09:54
Duplicate of #452

**Comment by DogHank** [comment] 2021-03-21 06:47
+1

**Comment by birhos** [comment] 2021-03-22 07:49
+1

**Comment by zhaopingfu** [comment] 2021-03-22 07:55
`pull_to_refresh: 1.6.4-nullsafety.0` can be use.

**Comment by kuromukira** [comment] 2021-03-22 08:54
`-nullsafety.0` does not work yet

**Comment by zhaopingfu** [comment] 2021-03-22 08:57
> `-nullsafety.0` does not work yet

use `1.6.4-nullsafety.0`, don\`t use `^1.6.4-nullsafety.0`

**Closed** 2021-03-27 06:26 UTC
